Fix readme

diff --git a/Dockerfile.runtime b/Dockerfile.runtime
--- a/Dockerfile.runtime
+++ b/Dockerfile.runtime
@@ -18,18 +18,23 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.
 
-
 ARG BASE_DIST
 ARG CUDA_VERSION
+ARG OPENCV_VERSION
+# Intra layer OpenCV
+FROM rbonghi/isaac-ros-base:opencv-${OPENCV_VERSION} as opencv_builder
+
+RUN cp /opt/opencv/build/OpenCV-*.tar.gz /OpenCV.tar.gz
+
 FROM nvidia/cuda:${CUDA_VERSION}-runtime-${BASE_DIST}
 
 # L4T variables
-ENV JETPACK=5.0.2
-ENV L4T=35.1
-ENV L4T_MINOR_VERSION=1.0
+ARG JETPACK=5.0.2
+ARG L4T=35.1
+ARG L4T_MINOR_VERSION=1.0
 # NVIDIA software
-ENV TENSORRT_VERSION=8.4
-ENV TRITON_VERSION=2.24.0
+ARG TENSORRT_VERSION=8.4
+ARG TRITON_VERSION=2.24.0
 
 # Disable terminal interaction for apt
 ENV DEBIAN_FRONTEND=noninteractive
@@ -57,10 +62,8 @@ RUN apt-get update && apt-get install -y \
     && rm -rf /var/lib/apt/lists/* \
     && apt-get clean
 
-# 
 # upgrade cmake - https://stackoverflow.com/a/56690743
 # this is needed to build some of the ROS2 packages
-#
 RUN wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | apt-key add - \
     && apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
     && apt-get update \
@@ -80,24 +83,13 @@ RUN apt-get update && apt-get install -y \
     && rm -rf /var/lib/apt/lists/* \
     && apt-get clean
 
+# remove other versions of Python3
+# workaround for 'Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS Development'
+RUN apt purge -y python3.9 libpython3.9* || echo "python3.9 not found, skipping removal" \
+    && ls -ll /usr/bin/python*
+
 # Set Python3 as default
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
-
-# Install OpenCV dependencies
-RUN apt-get update && apt-get install -y \
-        libavformat-dev \
-        libjpeg-dev \
-        libopenjp2-7-dev \
-        libpng-dev \
-        libpq-dev \
-        libswscale-dev \
-        libtbb2 \
-        libtbb-dev \
-        libtiff-dev \
-        pkg-config \
-        yasm \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
 
 # Install additional packages needed for ROS2 dependencies
 RUN apt-get update && apt-get install -y \
@@ -137,29 +129,30 @@ RUN python3 -m pip install -U \
 RUN python3 -m pip install -U \
     scikit-learn
 
-########### Sources and main Jetson reopo ##################
+########### Sources and main Jetson repo ###################
 
-RUN set -e -x && \
-    if [ "$(uname -m)" = "x86_64" ]; then \
-        apt-key adv --fetch-key https://repo.download.nvidia.com/jetson/jetson-ota-public.asc ; \
-        add-apt-repository "deb http://repo.download.nvidia.com/jetson/x86_64/focal r${L4T} main" ; \
-    else \
-        apt-key adv --fetch-key https://repo.download.nvidia.com/jetson/jetson-ota-public.asc ; \
-        echo "deb https://repo.download.nvidia.com/jetson/common r${L4T} main" >> /etc/apt/sources.list.d/nvidia-l4t-apt-source.list ; \
-    fi
-
-# TODO NVIDIA Jetson
-# Add libraries jetson_multimedia API
-# 
-# apt-get download nvidia-l4t-jetson-multimedia-api
-# dpkg -x nvidia-l4t-jetson-multimedia-api_35.1.0-20220825113828_arm64.deb /
+COPY scripts/variables.sh /variables.sh
+COPY scripts/install_nvidia_sources.sh install_nvidia_sources.sh
+RUN TERM=xterm bash install_nvidia_sources.sh ${L4T} \
+    && rm install_nvidia_sources.sh
 
 ########### VPI & TensorRT #################################
 
-RUN apt-get update && \
-    apt-get install -y tensorrt libnvvpi2 vpi2-dev && \
-    rm -rf /var/lib/apt/lists/* && \
-    apt-get clean
+RUN apt-get update \
+    && apt-get install -y tensorrt libnvvpi2 vpi2-dev \
+    && rm -rf /var/lib/apt/lists/* \
+    && apt-get clean
+
+ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/nvidia/vpi2/lib64"
+
+############ OpenCV ########################################
+
+# Load from OpenCV builder tar file
+COPY --from=opencv_builder /OpenCV.tar.gz /opt/OpenCV.tar.gz
+# Install OpenCV on system
+COPY scripts/install_opencv.sh /opt/install_opencv.sh
+RUN TERM=xterm bash /opt/install_opencv.sh ${OPENCV_VERSION} \
+    && rm /opt/install_opencv.sh
 
 ############################################################
 
@@ -176,12 +169,13 @@ RUN apt-get update && apt-get install -y \
         libbullet-dev \
         libtinyxml2-dev \
         libcunit1-dev \
-        libopencv-dev \
-        python3-opencv \
     && rm -rf /var/lib/apt/lists/* \
     && apt-get clean
 
 # NPP library
+# Error on aarch64
+# dpkg: error processing archive /var/cache/apt/archives/libnpp-11-4_11.4.0.228-1_arm64.deb
+#  trying to overwrite '/usr/local/cuda-11.4/lib64', which is also in package cuda-cuxxfilt-11-4 11.4.120-1
 #RUN apt-get update && apt-get install -y --no-install-recommends \
 #        libnpp-dev-11-4 \
 #&& rm -rf /var/lib/apt/lists/* \
