Minor fixes

diff --git a/Dockerfile.devel b/Dockerfile.devel
--- a/Dockerfile.devel
+++ b/Dockerfile.devel
@@ -85,8 +85,8 @@ RUN apt-get update && apt-get install -y \
 
 # remove other versions of Python3
 # workaround for 'Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS Development'
-RUN apt purge -y python3.9 libpython3.9* || echo "python3.9 not found, skipping removal" && \
-    ls -ll /usr/bin/python*
+RUN apt purge -y python3.9 libpython3.9* || echo "python3.9 not found, skipping removal" \
+    && ls -ll /usr/bin/python*
 
 # Set Python3 as default
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
